FROM underworldcode/underworld2_untested:dev_magnus
MAINTAINER romain.beucher@unimelb.edu

RUN apt-get update -qq
RUN DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends \
        python-tk

# UWGeodynamics
WORKDIR /opt
RUN git clone -b development https://github.com/rbeucher/UWGeodynamics.git
RUN pip install -e /opt/UWGeodynamics
